"""SQLModel schema + helpers for stored scene imagery.

A single table, ``EntityImage``, holds compressed (WebP) pictures generated by
the self-hosted diffusion backend. Images are keyed by a *subject* and a
*context* so that, e.g., a "desert wolf" and a "jungle wolf" are distinct
buckets of the creature ``wolf``, and "Jim in town" vs "Jim in the winter
desert" are distinct buckets of the NPC ``jim``.

Storage rules (enforced in ``store.py``, not here):
  - at most ``max_per_bucket`` (default 3) images per (kind, ref_slug, context_key);
  - when a subject's *intrinsic* appearance permanently changes (Jim loses a
    leg), every bucket for that subject is invalidated so fresh art regenerates;
  - a global LRU cap bounds total DB growth.
"""
from __future__ import annotations

import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from sqlalchemy import Column, Integer, String, LargeBinary, JSON
from sqlmodel import Field, SQLModel, create_engine
from sqlalchemy.engine import Engine


class ImageKind:
    """What a stored image depicts. Drives which table ``ref_slug`` points at."""
    PLACE = "place"        # -> world Entity.slug (type place)
    NPC = "npc"            # -> world Entity.slug (type npc)
    CREATURE = "creature"  # -> rules Monster.index_slug (or owned slug)
    ITEM = "item"          # -> world Entity.slug / rules Item
    PC = "pc"              # -> backend Character.name slug (player portrait)
    SCENE = "scene"        # -> a moment in play (multi-subject, never bucketed;
    #                          rendered with stored art of participants as
    #                          visual references — see store.generate_scene)

    ALL = {PLACE, NPC, CREATURE, ITEM, PC, SCENE}


def normalize_kind(kind: str) -> str:
    k = (kind or "").strip().lower()
    aliases = {"monster": ImageKind.CREATURE, "beast": ImageKind.CREATURE,
               "location": ImageKind.PLACE, "person": ImageKind.NPC,
               "character": ImageKind.NPC, "player": ImageKind.PC,
               "portrait": ImageKind.PC, "hero": ImageKind.PC}
    k = aliases.get(k, k)
    return k if k in ImageKind.ALL else ImageKind.CREATURE


_SLUG_RE = re.compile(r"[^a-z0-9]+")


def slugify(text: str) -> str:
    """Lowercase, hyphenated, url-safe handle used for refs and context keys."""
    s = _SLUG_RE.sub("-", (text or "").strip().lower()).strip("-")
    return s or "unknown"


def context_key(context: Optional[str]) -> str:
    """Normalize a free-text context ("Desert, at night") to a stable bucket key.

    An empty/None context collapses to ``"default"`` so subjects that never
    change with their surroundings still get a single bucket.
    """
    key = slugify(context or "")
    return key if key and key != "unknown" else "default"


class EntityImage(SQLModel, table=True):
    __tablename__ = "entity_image"

    id: Optional[int] = Field(default=None, primary_key=True)

    # Subject identity.
    kind: str = Field(sa_column=Column(String, nullable=False, index=True))
    ref_slug: str = Field(sa_column=Column(String, nullable=False, index=True))
    # Environment / situational bucket (e.g. "desert", "town-winter").
    context_key: str = Field(default="default", sa_column=Column(String, index=True))

    # A short, human-readable label for the subject as depicted.
    caption: Optional[str] = Field(default=None, sa_column=Column(String))
    # The exact positive prompt sent to the diffusion backend.
    prompt: Optional[str] = Field(default=None, sa_column=Column(String))
    # Hash of the *intrinsic* appearance descriptor. When a subject's canonical
    # look changes permanently, its new descriptor hash won't match the old
    # rows, so they can be swept.
    descriptor_hash: Optional[str] = Field(default=None, sa_column=Column(String, index=True))

    # Compressed image payloads (WebP bytes).
    image: bytes = Field(sa_column=Column(LargeBinary, nullable=False))
    thumb: Optional[bytes] = Field(default=None, sa_column=Column(LargeBinary))
    width: int = Field(default=0)
    height: int = Field(default=0)
    byte_size: int = Field(default=0)

    seed: Optional[int] = Field(default=None, sa_column=Column(Integer))
    meta: Optional[Any] = Field(default=None, sa_column=Column(JSON))

    # Usage bookkeeping for LRU eviction + "random draw" fairness.
    use_count: int = Field(default=0, index=True)
    world_day: int = Field(default=0)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    last_used_at: datetime = Field(default_factory=datetime.utcnow)


def get_engine(database_url: Optional[str] = None) -> Engine:
    """Default to the backend's ``oracle.db`` (shared with rules/world)."""
    if database_url is None:
        database_url = os.getenv("DATABASE_URL")
    if database_url is None:
        backend_db = Path(__file__).resolve().parent.parent / "oracle-dm-backend" / "oracle.db"
        database_url = f"sqlite:///{backend_db}"
    connect_args = {"check_same_thread": False} if database_url.startswith("sqlite") else {}
    return create_engine(database_url, echo=False, connect_args=connect_args)
